apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashcards
  labels:
    app: flashcards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flashcards
  template:
    metadata:
      labels:
        app: flashcards
    spec:
      containers:
        - name: flashcards
          image: ghcr.io/haricazorla/flashcards-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: spring.datasource.url
              value: jdbc:postgresql://postgres-service:5432/flashcards
            - name: spring.datasource.username
              value: postgres
            - name: spring.datasource.password
              value: "ANY_SECRET"
