apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
  labels:
    app: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
        - name: expense-tracker
          image: ghcr.io/haricazorla/expense-tracker:1.0
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     memory: "100Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "200Mi"
          #     cpu: "500m"
          env:
            - name: spring.datasource.url
              value: jdbc:postgresql://postgres-service:5432/expensetracker
            - name: spring.datasource.username
              value: postgres
            - name: spring.datasource.password
              value: "ANY_SECRET"
